services:
  ai-prompt-manager:
    container_name: ai-prompt-manager
    image: neytor/ai-prompt-manager
    ports:
      - "8102:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/prod.db
      NODE_OPTIONS: --max-old-space-size=1024
    volumes:
      # Bind mount: persiste la base de datos en ./data del repo (recomendado)
      - ./data:/app/data
      # Bind mount para uploads/archivos de usuario
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
